name: Changesets

on:
  push:
    branches: [main, remote-dom]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Changesets ðŸ¦‹
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # This (plus the GITHUB_TOKEN on the changeset action) allow other workflows to run on the PR that changesets creates.
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare
      # @see https://github.com/changesets/action
      - uses: changesets/action@v1
        with:
          title: 'Publish packages ðŸš€'
          commit: 'Publish packages'
          version: pnpm version-bump
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
